# Generated by Django 3.2.8 on 2022-01-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eycmedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediatDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagemedia', models.ImageField(blank=True, null=True, upload_to='static/img/eycmedia')),
                ('url', models.URLField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eycmedia.mediaseasonm')),
            ],
        ),
    ]
