# Generated by Django 3.2.8 on 2022-01-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eycmedia', '0002_mediatdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediatdetails',
            name='topic',
        ),
        migrations.DeleteModel(
            name='MediaSeasonM',
        ),
        migrations.DeleteModel(
            name='MediatDetails',
        ),
    ]
