# Generated by Django 3.2.8 on 2022-01-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eycmedia', '0004_photoscenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('video', models.FileField(blank=True, null=True, upload_to='static/img/videoscenter')),
            ],
        ),
    ]
