# Generated by Django 3.2.8 on 2022-01-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eycmedia', '0005_videoscenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoscenter',
            name='title_en',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoscenter',
            name='title_en',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
