# Generated by Django 3.2.8 on 2022-01-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20220106_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='research',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='youth',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img/mediamodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='research',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img/research'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technology',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img/technology'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='youth',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img/youth'),
            preserve_default=False,
        ),
    ]
