# Generated by Django 3.2.8 on 2022-01-13 11:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20220108_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='desc_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='research',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='research',
            name='desc_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='technology',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='technology',
            name='desc_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='youth',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='youth',
            name='desc_en',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
