# Generated by Django 3.2.8 on 2021-11-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_counters_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='name',
            field=models.CharField(default='عدادات الصفحه الرئيسيه', editable=False, max_length=50),
        ),
    ]
