# Generated by Django 3.2.8 on 2021-11-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_imghome'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
