# Generated by Django 3.2.8 on 2021-12-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cadres_carrier_partnerships_radio_technology_units_welcomescreen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrImage', models.ImageField(blank=True, null=True, upload_to='static/img/md')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('ScImage', models.ImageField(blank=True, null=True, upload_to='static/img/md')),
                ('ScImage2', models.ImageField(blank=True, null=True, upload_to='static/img/md')),
                ('ScImage3', models.ImageField(blank=True, null=True, upload_to='static/img/md')),
                ('ScImage4', models.ImageField(blank=True, null=True, upload_to='static/img/md')),
                ('ScImage5', models.ImageField(blank=True, null=True, upload_to='static/img/md')),
            ],
        ),
    ]
