# Generated by Django 3.2.8 on 2021-12-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211228_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Environment',
        ),
        migrations.DeleteModel(
            name='Human_Rights',
        ),
        migrations.DeleteModel(
            name='Peace',
        ),
        migrations.DeleteModel(
            name='Political_participation',
        ),
        migrations.DeleteModel(
            name='Women',
        ),
    ]
