# Generated by Django 3.2.8 on 2021-12-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20211228_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Units',
        ),
    ]
