# Generated by Django 3.2.8 on 2022-01-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_units'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
