# Generated by Django 3.2.8 on 2022-01-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partnerships',
        ),
    ]
