# Generated by Django 3.2.8 on 2022-01-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_partnerships'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadres',
        ),
        migrations.DeleteModel(
            name='Radio',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
