# Generated by Django 3.2.8 on 2022-01-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20220123_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgHome',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='WelcomeScreen',
        ),
    ]
