# Generated by Django 3.2.8 on 2022-01-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20220123_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counters',
            old_name='courses',
            new_name='youth',
        ),
    ]
