# Generated by Django 3.2.8 on 2022-01-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carriers', '0002_auto_20220105_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='peace',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
