# Generated by Django 3.2.8 on 2022-01-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carriers', '0003_peace_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peace',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
