# Generated by Django 3.2.8 on 2022-01-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carriers', '0004_alter_peace_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peace',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img/peace'),
            preserve_default=False,
        ),
    ]
