# Generated by Django 3.2.8 on 2022-01-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carriers', '0005_alter_peace_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='human_rights',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='political_participation',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='women',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img/environment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='human_rights',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img/human_rights'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='political_participation',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img/political_participation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='women',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img/women'),
            preserve_default=False,
        ),
    ]
