# Generated by Django 3.2.8 on 2022-01-13 11:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carriers', '0006_auto_20220108_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='environment',
            name='desc_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='human_rights',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='human_rights',
            name='desc_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='peace',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='peace',
            name='desc_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='political_participation',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='political_participation',
            name='desc_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='women',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='women',
            name='desc_en',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
