# Generated by Django 3.2.8 on 2022-01-17 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodes',
            name='link',
        ),
        migrations.AddField(
            model_name='all_season',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radio.episodes'),
            preserve_default=False,
        ),
    ]
