# Generated by Django 3.2.8 on 2022-01-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20220117_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_season',
            name='season_image',
        ),
        migrations.RemoveField(
            model_name='all_season',
            name='test',
        ),
        migrations.AddField(
            model_name='episodes',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radio.all_season'),
            preserve_default=False,
        ),
    ]
