# Generated by Django 3.2.8 on 2022-01-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_auto_20220117_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='episode_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
