# Generated by Django 3.2.8 on 2022-01-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_episodes_episode_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_season',
            old_name='season_name_en',
            new_name='season_name',
        ),
        migrations.AddField(
            model_name='episodes',
            name='episode_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
