# Generated by Django 3.2.8 on 2022-01-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_auto_20220122_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_season',
            old_name='season_name',
            new_name='season_name_en',
        ),
    ]
