# Generated by Django 3.2.8 on 2022-01-23 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_en',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
