# Generated by Django 3.2.8 on 2021-11-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='branch_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
