# Generated by Django 3.2.8 on 2021-12-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_join'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='join',
            new_name='Volunteering',
        ),
    ]
