# Generated by Django 3.2.8 on 2021-12-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_rename_join_volunteering'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteering',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
