# Generated by Django 3.2.8 on 2021-12-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_volunteering_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch_V_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteering',
            name='active',
        ),
    ]
