# Generated by Django 3.2.8 on 2021-12-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20211201_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='switch_v_form',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
