# Generated by Django 3.2.8 on 2021-12-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messeage',
            new_name='message',
        ),
    ]
