# Generated by Django 3.2.8 on 2021-12-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_rename_messeage_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branches',
            name='branch_address_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='branches',
            name='branch_name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
