# Generated by Django 3.2.8 on 2021-12-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_auto_20211213_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='title_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
