# Generated by Django 3.2.8 on 2022-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_auto_20211213_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnerships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200)),
                ('partner_name_en', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
    ]
