# Generated by Django 3.2.8 on 2022-01-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_achievements_episodes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Episodes',
            new_name='Desc_Achievements',
        ),
    ]
