# Generated by Django 3.2.8 on 2022-01-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0019_rename_episodes_desc_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desc_achievements',
            name='link',
        ),
        migrations.DeleteModel(
            name='Achievements',
        ),
        migrations.DeleteModel(
            name='Desc_Achievements',
        ),
    ]
