# Generated by Django 3.2.8 on 2022-01-23 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_auto_20220123_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerships',
            name='partner_bio',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='partnerships',
            name='partner_bio_en',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
