# Generated by Django 3.2.8 on 2022-01-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0021_auto_20220123_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteering',
            old_name='v_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='volunteering',
            old_name='v_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='volunteering',
            old_name='v_phone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='volunteering',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteering',
            name='national_id',
            field=models.IntegerField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
