# Generated by Django 3.2.8 on 2022-01-24 12:58

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0022_auto_20220124_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteering',
            name='national_id',
            field=models.CharField(max_length=14, validators=[about.models.only_int]),
        ),
    ]
