# Generated by Django 3.2.8 on 2022-01-23 09:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_auto_20220123_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='desc_en',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='title_en',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desc_achievements',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='desc_achievements',
            name='desc_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
