# Generated by Django 3.2.8 on 2022-01-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0005_auto_20220123_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='image',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='link',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='name',
        ),
        migrations.CreateModel(
            name='Technology_Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/tech')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('url_two', models.URLField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.technology')),
            ],
        ),
    ]
